# Ubuntu + python
FROM ubuntu:22.04

RUN apt-get update && apt-get upgrade


# apt-get install openjdk-8-jdk
# apt-get install curl zip unzip
# curl -s "https://get.sdkman.io" | bash 
# source "$HOME/.sdkman/bin/sdkman-init.sh"
# sbt new playframework/play-scala-seed.g8